#!/usr/bin/env node
/*
 * convert-fonts.mjs -- regenerate the pm-font font tables from the C headers.
 *
 * The Rust tables in rust/crates/pm-font/src/fonts/ are generated, not
 * hand-typed: this script parses the `const uint8_t fontNxM[]` arrays in
 * lib/Platinenmacher/fonts/ and emits byte-for-byte identical Rust arrays,
 * keeping the original line breaks and trailing comments so a reviewer can
 * diff the two side by side.
 *
 * Usage:
 *   node rust/tools/convert-fonts.mjs            # (re)write the Rust tables
 *   node rust/tools/convert-fonts.mjs --check    # fail if they are stale
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');
const C_FONTS = path.join(REPO, 'lib', 'Platinenmacher', 'fonts');
const OUT_DIR = path.join(REPO, 'rust', 'crates', 'pm-font', 'src', 'fonts');

// id -> expected (width, height) taken from the font name itself; the parser
// asserts the array header agrees, so a mis-parsed file cannot slip through.
const FONTS = ['6x8', '8x8', '8x16', '10x14', '12x8', '13x8', '16x8', '16x16'];

/** Locate the translation unit that actually defines `font<id>[]`. */
function sourceFor(id) {
    for (const ext of ['.c', '.h']) {
        const p = path.join(C_FONTS, `font${id}${ext}`);
        if (fs.existsSync(p) && fs.readFileSync(p, 'utf8').includes(`font${id}[] =`)) return p;
    }
    throw new Error(`no definition of font${id}[] found in ${C_FONTS}`);
}

/** Extract the `{ ... }` initialiser body of `symbol`, brace balanced. */
function arrayBody(src, symbol) {
    const decl = src.indexOf(`${symbol}[] =`);
    if (decl < 0) throw new Error(`${symbol}[] not found`);
    const open = src.indexOf('{', decl);
    if (open < 0) throw new Error(`${symbol}: no opening brace`);
    let depth = 0;
    for (let i = open; i < src.length; i++) {
        if (src[i] === '{') depth++;
        else if (src[i] === '}' && --depth === 0) return src.slice(open + 1, i);
    }
    throw new Error(`${symbol}: unbalanced braces`);
}

/** Split a source line into its code part and its trailing comment (if any). */
function splitComment(line) {
    const slash = line.indexOf('//');
    const block = line.indexOf('/*');
    if (slash >= 0 && (block < 0 || slash < block)) {
        return [line.slice(0, slash), line.slice(slash + 2).replace(/\s+$/, '').trim()];
    }
    if (block >= 0) {
        const end = line.indexOf('*/', block);
        const body = end < 0 ? line.slice(block + 2) : line.slice(block + 2, end);
        return [line.slice(0, block) + (end < 0 ? '' : line.slice(end + 2)), body.trim()];
    }
    return [line, ''];
}

/** Parse the array body into `{ bytes, rows }`, one row per C source line. */
function parseRows(body) {
    const rows = [];
    const bytes = [];
    for (const raw of body.split('\n')) {
        const [code, comment] = splitComment(raw);
        const row = [];
        for (const tok of code.match(/0[xX][0-9a-fA-F]+|\d+/g) ?? []) {
            const v = Number(tok);
            if (!Number.isInteger(v) || v < 0 || v > 255) throw new Error(`byte out of range: ${tok}`);
            row.push(v);
            bytes.push(v);
        }
        if (row.length || comment) rows.push({ row, comment });
    }
    while (rows.length && !rows[rows.length - 1].row.length) rows.pop();
    return { bytes, rows };
}

const ROTATIONS = ['Rotate0', 'Rotate90', 'Rotate180', 'Rotate270'];

function render(id, cFile, name, bytes, rows) {
    const screaming = `FONT${id.toUpperCase()}`;
    const [w, h, offset, rotation] = bytes;
    const rel = path.relative(REPO, cFile).split(path.sep).join('/');
    const out = [];
    out.push(`//! \`${name}\` font table.`);
    out.push('//!');
    out.push(`//! @generated by \`node rust/tools/convert-fonts.mjs\` from \`${rel}\`.`);
    out.push('//! Do not edit by hand -- edit the C table and re-run the converter.');
    out.push('');
    out.push('use crate::Font;');
    out.push('');
    out.push(`/// The \`${name}\` font: ${w}x${h} glyphs starting at ASCII 0x${offset
        .toString(16)
        .padStart(2, '0')}, rotation ${ROTATIONS[rotation]}.`);
    out.push(`pub static ${screaming}: Font = Font::from_array(&${screaming}_RAW, "${name}");`);
    out.push('');
    out.push(`/// Raw table, byte-identical to \`font${id}[]\` in \`${rel}\`.`);
    out.push('///');
    out.push('/// The first four bytes are the header `[width, height, ascii_offset, rotation]`,');
    out.push('/// exactly as `font_load_from_array()` expects them.');
    out.push('#[rustfmt::skip]');
    out.push(`pub static ${screaming}_RAW: [u8; ${bytes.length}] = [`);
    for (const { row, comment } of rows) {
        const cells = row.map((b) => `0x${b.toString(16).toUpperCase().padStart(2, '0')},`).join(' ');
        if (!cells) {
            if (comment) out.push(`    // ${comment}`);
            continue;
        }
        out.push(`    ${cells}${comment ? ` // ${comment}` : ''}`.replace(/\s+$/, ''));
    }
    out.push('];');
    out.push('');
    return out.join('\n');
}

function renderMod(entries) {
    // Emitted in the shape `cargo fmt` produces (modules and re-exports sorted
    // by rustfmt's `reorder_modules`, ALL_FONTS packed onto one line) so that
    // formatting the workspace never makes the generated file look stale.
    const sorted = [...entries].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
    const out = [];
    out.push('//! Font tables ported from `lib/Platinenmacher/fonts/`.');
    out.push('//!');
    out.push('//! @generated by `node rust/tools/convert-fonts.mjs`. Do not edit by hand.');
    out.push('');
    out.push('use crate::Font;');
    out.push('');
    for (const e of sorted) out.push(`mod font${e.id};`);
    out.push('');
    for (const e of sorted) out.push(`pub use font${e.id}::{${e.screaming}, ${e.screaming}_RAW};`);
    out.push('');
    out.push('/// Every ported font, in the order the C tables are listed in `fonts/`.');
    out.push(`pub static ALL_FONTS: [&Font; ${entries.length}] = [`);
    out.push('    ' + entries.map((e) => `&${e.screaming},`).join(' '));
    out.push('];');
    out.push('');
    return out.join('\n');
}

const check = process.argv.includes('--check');
const written = [];
const entries = [];
let stale = 0;

for (const id of FONTS) {
    const cFile = sourceFor(id);
    const src = fs.readFileSync(cFile, 'utf8');
    const { bytes, rows } = parseRows(arrayBody(src, `font${id}`));
    const nameMatch = src.match(new RegExp(`font${id}_name\\s*=\\s*"([^"]*)"`));
    const name = nameMatch ? nameMatch[1] : id;

    const [w, h] = id.split('x').map(Number);
    if (bytes.length < 5) throw new Error(`font${id}: table too short`);
    if (bytes[0] !== w || bytes[1] !== h) {
        throw new Error(`font${id}: header says ${bytes[0]}x${bytes[1]}, name says ${w}x${h}`);
    }
    if (bytes[3] > 3) throw new Error(`font${id}: bad rotation ${bytes[3]}`);

    const screaming = `FONT${id.toUpperCase()}`;
    entries.push({ id, screaming });
    written.push({
        file: path.join(OUT_DIR, `font${id}.rs`),
        text: render(id, cFile, name, bytes, rows),
    });
    console.log(`font${id}: ${bytes.length} bytes (${rows.length} rows) from ${path.relative(REPO, cFile)}`);
}

written.push({ file: path.join(OUT_DIR, 'mod.rs'), text: renderMod(entries) });

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const { file, text } of written) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === text) continue;
    if (check) {
        console.error(`stale: ${path.relative(REPO, file)}`);
        stale++;
    } else {
        fs.writeFileSync(file, text);
    }
}

if (check && stale) {
    console.error(`${stale} generated file(s) out of date; run: node rust/tools/convert-fonts.mjs`);
    process.exit(1);
}
console.log(check ? 'all generated font tables are up to date' : 'font tables regenerated');
