[package]
name = "pm-parser"
description = "Serial command parser, XML pull parser and the IndiaNavi config file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
pm-core.workspace = true
