//! Font tables ported from `lib/Platinenmacher/fonts/`.
//!
//! @generated by `node rust/tools/convert-fonts.mjs`. Do not edit by hand.

use crate::Font;

mod font10x14;
mod font12x8;
mod font13x8;
mod font16x16;
mod font16x8;
mod font6x8;
mod font8x16;
mod font8x8;

pub use font10x14::{FONT10X14, FONT10X14_RAW};
pub use font12x8::{FONT12X8, FONT12X8_RAW};
pub use font13x8::{FONT13X8, FONT13X8_RAW};
pub use font16x16::{FONT16X16, FONT16X16_RAW};
pub use font16x8::{FONT16X8, FONT16X8_RAW};
pub use font6x8::{FONT6X8, FONT6X8_RAW};
pub use font8x16::{FONT8X16, FONT8X16_RAW};
pub use font8x8::{FONT8X8, FONT8X8_RAW};

/// Every ported font, in the order the C tables are listed in `fonts/`.
pub static ALL_FONTS: [&Font; 8] = [
    &FONT6X8, &FONT8X8, &FONT8X16, &FONT10X14, &FONT12X8, &FONT13X8, &FONT16X8, &FONT16X16,
];
