name: Build IndiaNavi Firmware with platformio 
on:
  push:
    branches: 
      - 'main'
      - 'ci'
  pull_request:

jobs:
  platformio_run_native_tests:
    uses: ./.github/workflows/platformio_test_native.yml
 
  build_and_upload:
    uses: ./.github/workflows/platformio_build.yml
    