name: Build IndiaNavi Firmware with platformio 
on:
  push:
    branches: 
      - 'main'
      - 'ci'
  pull_request:

jobs:
  install_platformio_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.1

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio         
    - name: Run PlatformIO build on selected platforms
      run: platformio run
      
    - name: Upload debug.bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest_debug.bin
        path: .pio/build/esp32dev_debug/firmware.bin
        retention-days: 5   

    - name: Upload .bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest.bin
        path: .pio/build/esp32dev_release/firmware.bin
        retention-days: 5   
        
    - name: Upload .elf file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest_debug.elf
        path: .pio/build/esp32dev_debug/firmware.elf
        retention-days: 5   