name: Deploy Firmware images 
on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed
  
jobs:
  download_binareis_and_upload_to_s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: firmware_debug.bin
    - uses: actions/download-artifact@v3
      with:
        name: firmware_.bin
    - name: make deploy folder
      if: success()
      run: |
        mkdir deploy
        cp firmware.bin ./deploy/firmware_latest.bin
        cp firmware_debug.bin ./deploy/firmware_latest_debug.bin
        sha256sum firmware.bin | cut -d' ' -f1 > ./deploy/firmware_latest.sha
        sha256sum firmware_debug.bin | cut -d' ' -f1 > ./deploy/firmware_latest_debug.sha
        cp firmware.bin ./deploy/firmware_$(git describe --abbrev=7 --always).bin
        cp firmware_debug.bin ./deploy/firmware_$(git describe --abbrev=7 --always)_debug.bin
        sha256sum firmware.bin | cut -d' ' -f1 > ./deploy/firmware_$(git describe --abbrev=7 --always).sha
        sha256sum firmware_debug.bin | cut -d' ' -f1 > ./deploy/firmware_$(git describe --abbrev=7 --always)_debug.sha

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "./deploy"