name: Deploy Firmware images to S3
on:
  workflow_run:
    workflows: ['Build IndiaNavi Firmware with platformio']
    types:
      - completed
  
jobs:
  download_binaries_and_upload_to_s3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [indianavi_s3_n16r8_debug, indianavi_s3_n16r8_release]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: firmware_${{ matrix.target }}.bin 
    - name: make deploy folder
      if: success()
      run: |
        mkdir deploy
        cp firmware_${{ matrix.target }}.bin  ./deploy/firmware_${{ matrix.target }}_latest.bin
        sha256sum firmware_${{ matrix.target }}_release.bin  | cut -d' ' -f1 > ./deploy/firmware_${{ matrix.target }}_latest.sha
        cp firmware_${{ matrix.target }}.bin  ./deploy/firmware_${{ matrix.target }}_$(git describe --abbrev=7 --always).bin
        sha256sum firmware_${{ matrix.target }}.bin  | cut -d' ' -f1 > ./deploy/firmware_${{ matrix.target }}_$(git describe --abbrev=7 --always).sha

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "./deploy"