name: Build device binaries using platform.io

on:
  workflow_call:
  
jobs:
  platformio_run:
    strategy:
      matrix:
        target: [esp32dev_debug, esp32dev_release, indianavi_s3_n16r8_debug, indianavi_s3_n16r8_release, linux_native]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2.2.1

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-platformio-${{ matrix.target }}

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on embedded platforms
      run: platformio run -e ${{ matrix.target }}

    - id: hash
      uses: pr-mpt/actions-commit-hash@v1
      
    - name: Upload debug.bin file
      if: (success() and ${{ matrix.target }}!= "linux_native")
      uses: actions/upload-artifact@v2
      with:
        name: firmware_${{ matrix.target }}.bin
        path: .pio/build/${{ matrix.target }}/firmware.bin
        retention-days: 5   

    - name: Upload linux binary file
      if: (success() and ${{ matrix.target }} == "linux_native"
      uses: actions/upload-artifact@v2
      with:
        name: indianavi
        path: .pio/build/${{ matrix.target }}/program
        retention-days: 5   
