name: Build device binaries using platform.io

on:
  workflow_call:
  
jobs:
  platformio_run:
    strategy:
      matrix:
        target: [indianavi_s3_n16r8_debug, indianavi_s3_n16r8_release, linux_native]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Set up Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on embedded platforms
      run: platformio run -e ${{ matrix.target }}

    - id: hash
      uses: pr-mpt/actions-commit-hash@v2
      
    - name: Upload debug.bin file
      if: (success() && !contains(matrix.target, 'linux_native'))
      uses: actions/upload-artifact@v3
      with:
        name: firmware_${{ matrix.target }}.bin
        path: .pio/build/${{ matrix.target }}/firmware.bin
        retention-days: 5   

    - name: make deploy folder
      if: (success() && !contains(matrix.target, 'linux_native'))
      run: |
        mkdir deploy
        cp .pio/build/${{ matrix.target }}/firmware.bin  ./deploy/firmware_${{ matrix.target }}_latest.bin
        sha256sum firmware_${{ matrix.target }}_release.bin  | cut -d' ' -f1 > ./deploy/firmware_${{ matrix.target }}_latest.sha
        cp .pio/build/${{ matrix.target }}/firmware.bin  ./deploy/firmware_${{ matrix.target }}_$(git describe --abbrev=7 --always).bin
        sha256sum firmware_${{ matrix.target }}.bin  | cut -d' ' -f1 > ./deploy/firmware_${{ matrix.target }}_$(git describe --abbrev=7 --always).sha

    - name: Upload linux binary file
      if: (success() && contains(matrix.target, 'linux_native'))
      uses: actions/upload-artifact@v3
      with:
        name: indianavi
        path: .pio/build/${{ matrix.target }}/program
        retention-days: 5
    
    - name: Deploy to S3
      if: (success() && !contains(matrix.target, 'linux_native'))
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "./deploy"