name: Build device binaries using platform.io

on:
  workflow_call:
  
jobs:
  platformio_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2.2.1

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-platformio
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on embedded platforms
      run: platformio run -e esp32dev_debug -e esp32dev_release
      
    - name: Upload debug.bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest_debug.bin
        path: .pio/build/esp32dev_debug/firmware.bin
        retention-days: 5   

    - name: Upload .bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest.bin
        path: .pio/build/esp32dev_release/firmware.bin
        retention-days: 5   
        
    - name: Upload .elf file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_latest_debug.elf
        path: .pio/build/esp32dev_debug/firmware.elf
        retention-days: 5   
