name: Build device binaries using platform.io

on:
  workflow_call:
  
jobs:
  platformio_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2.2.1

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-platformio
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install pio and its dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO build on embedded platforms
      run: platformio run -e esp32dev_debug -e esp32dev_release -e indianavi_s3_n16r8_debug -e indianavi_s3_n16r8_release -e linux_native

    - id: hash
      uses: pr-mpt/actions-commit-hash@v1
      
    - name: Upload debug.bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_debug.bin
        path: .pio/build/esp32dev_debug/firmware.bin
        retention-days: 5   

    - name: Upload .bin file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/esp32dev_release/firmware.bin
        retention-days: 5   
        
    - name: Upload .elf file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware_debug.elf
        path: .pio/build/esp32dev_debug/firmware.elf
        retention-days: 5   

    - name: Upload debug.bin file for S3
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: s3_firmware_debug.bin
        path: .pio/build/indianavi_s3_n16r8_debug/firmware.bin
        retention-days: 5   

    - name: Upload .bin file for S3
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: s3_firmware.bin
        path: .pio/build/indianavi_s3_n16r8_release/firmware.bin
        retention-days: 5   
        
    - name: Upload .elf file for S3
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: s3_firmware_debug.elf
        path: .pio/build/indianavi_s3_n16r8_debug/firmware.elf
        retention-days: 5   

    - name: Upload linux binary file
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: indianavi
        path: .pio/build/linux_native/program
        retention-days: 5   
